version: '3.1'

services:
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass secret --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data: